begin;

create table if not exists public.operation_logs (
  id bigint generated by default as identity primary key,
  application_id bigint,
  actor_user_id uuid not null,
  actor_name text not null,
  actor_role text not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

comment on table public.operation_logs is
  '审批与删除等关键动作的审计日志，主记录删除后仍可在此追溯';

comment on column public.operation_logs.application_id is '关联的 applications.id，删除后保留原始编号';
comment on column public.operation_logs.actor_user_id is '执行操作的登录用户 ID';
comment on column public.operation_logs.actor_name is '执行操作时记录下来的姓名或账号';
comment on column public.operation_logs.actor_role is '执行操作时的角色';
comment on column public.operation_logs.action is '操作类型，例如 approve_application / reject_application / delete_rejected_application';
comment on column public.operation_logs.details is '操作附加信息，例如文件编号、教师、驳回原因、批量来源等';
comment on column public.operation_logs.created_at is '日志写入时间';

create index if not exists operation_logs_application_id_idx
  on public.operation_logs (application_id);

create index if not exists operation_logs_actor_user_id_idx
  on public.operation_logs (actor_user_id);

create index if not exists operation_logs_created_at_idx
  on public.operation_logs (created_at desc);

alter table public.operation_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'operation_logs'
      and policyname = 'operation_logs_admin_select'
  ) then
    create policy operation_logs_admin_select
      on public.operation_logs
      for select
      to authenticated
      using (
        exists (
          select 1
          from public.profiles requester
          where requester.id = auth.uid()
            and requester.role = 'admin'
        )
      );
  end if;
end;
$$;

revoke all on table public.operation_logs from public;
grant select on table public.operation_logs to authenticated;

update public.applications
set status = '待审批'
where status is null;

update public.applications
set
  approval_time = null,
  approver_name = null,
  rejection_reason = null
where status = '待审批';

update public.applications
set
  approval_time = coalesce(approval_time, timezone('utc', now())),
  approver_name = coalesce(nullif(btrim(coalesce(approver_name, '')), ''), '系统补录'),
  rejection_reason = null
where status = '已通过';

update public.applications
set
  approval_time = coalesce(approval_time, timezone('utc', now())),
  approver_name = coalesce(nullif(btrim(coalesce(approver_name, '')), ''), '系统补录'),
  rejection_reason = coalesce(nullif(btrim(coalesce(rejection_reason, '')), ''), '未填写')
where status = '已驳回';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'applications_status_allowed_chk'
      and conrelid = 'public.applications'::regclass
  ) then
    alter table public.applications
      add constraint applications_status_allowed_chk
      check (status in ('待审批', '已通过', '已驳回'));
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'applications_pending_metadata_empty_chk'
      and conrelid = 'public.applications'::regclass
  ) then
    alter table public.applications
      add constraint applications_pending_metadata_empty_chk
      check (
        status <> '待审批'
        or (
          approval_time is null
          and nullif(btrim(coalesce(approver_name, '')), '') is null
          and nullif(btrim(coalesce(rejection_reason, '')), '') is null
        )
      );
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'applications_processed_metadata_required_chk'
      and conrelid = 'public.applications'::regclass
  ) then
    alter table public.applications
      add constraint applications_processed_metadata_required_chk
      check (
        status not in ('已通过', '已驳回')
        or (
          approval_time is not null
          and nullif(btrim(coalesce(approver_name, '')), '') is not null
        )
      );
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'applications_approved_reason_empty_chk'
      and conrelid = 'public.applications'::regclass
  ) then
    alter table public.applications
      add constraint applications_approved_reason_empty_chk
      check (
        status <> '已通过'
        or nullif(btrim(coalesce(rejection_reason, '')), '') is null
      );
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'applications_rejected_reason_required_chk'
      and conrelid = 'public.applications'::regclass
  ) then
    alter table public.applications
      add constraint applications_rejected_reason_required_chk
      check (
        status <> '已驳回'
        or nullif(btrim(coalesce(rejection_reason, '')), '') is not null
      );
  end if;
end;
$$;

create or replace function public.admin_change_application_status(
  target_application_id bigint,
  target_status text,
  target_approval_time timestamptz default null,
  target_rejection_reason text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_role text;
  requester_name text;
  normalized_status text;
  normalized_reason text;
  normalized_time timestamptz;
  updated_app public.applications%rowtype;
begin
  select
    coalesce(role, 'teacher'),
    coalesce(nullif(btrim(coalesce(full_name, '')), ''), nullif(btrim(coalesce(username, '')), ''), '未命名用户')
  into requester_role, requester_name
  from public.profiles
  where id = auth.uid();

  requester_role := coalesce(requester_role, 'teacher');
  requester_name := coalesce(requester_name, '未命名用户');
  normalized_status := btrim(coalesce(target_status, ''));

  if requester_role <> 'admin' then
    raise exception '只有管理员可以更新审批状态';
  end if;

  if normalized_status not in ('已通过', '已驳回') then
    raise exception '仅支持通过或驳回待审批记录';
  end if;

  normalized_time := coalesce(target_approval_time, timezone('utc', now()));

  if normalized_status = '已驳回' then
    normalized_reason := nullif(btrim(coalesce(target_rejection_reason, '')), '');
    if normalized_reason is null then
      raise exception '驳回时必须填写原因';
    end if;
  else
    normalized_reason := null;
  end if;

  update public.applications
  set
    status = normalized_status,
    approval_time = normalized_time,
    approver_name = requester_name,
    rejection_reason = normalized_reason
  where id = target_application_id
    and status = '待审批'
  returning * into updated_app;

  if updated_app.id is null then
    raise exception '未找到可更新的待审批记录';
  end if;

  insert into public.operation_logs (
    application_id,
    actor_user_id,
    actor_name,
    actor_role,
    action,
    details
  )
  values (
    updated_app.id,
    auth.uid(),
    requester_name,
    requester_role,
    case when normalized_status = '已通过' then 'approve_application' else 'reject_application' end,
    jsonb_build_object(
      'mode', 'single',
      'status', updated_app.status,
      'teacher_name', updated_app.teacher_name,
      'file_name', updated_app.file_name,
      'approval_time', updated_app.approval_time,
      'rejection_reason', updated_app.rejection_reason
    )
  );

  return updated_app.id;
end;
$$;

comment on function public.admin_change_application_status(bigint, text, timestamptz, text) is
  '管理员更新单条待审批记录的状态，并写入操作日志';

create or replace function public.admin_bulk_change_application_status(
  target_application_ids bigint[],
  target_status text,
  target_approval_time timestamptz default null,
  target_rejection_reason text default null
)
returns bigint[]
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_role text;
  requester_name text;
  normalized_status text;
  normalized_reason text;
  normalized_time timestamptz;
  normalized_ids bigint[];
  updated_ids bigint[];
begin
  select
    coalesce(role, 'teacher'),
    coalesce(nullif(btrim(coalesce(full_name, '')), ''), nullif(btrim(coalesce(username, '')), ''), '未命名用户')
  into requester_role, requester_name
  from public.profiles
  where id = auth.uid();

  requester_role := coalesce(requester_role, 'teacher');
  requester_name := coalesce(requester_name, '未命名用户');
  normalized_status := btrim(coalesce(target_status, ''));
  normalized_ids := array(
    select distinct unnest(coalesce(target_application_ids, '{}'::bigint[]))
  );

  if requester_role <> 'admin' then
    raise exception '只有管理员可以批量更新审批状态';
  end if;

  if coalesce(array_length(normalized_ids, 1), 0) = 0 then
    raise exception '请先选择至少一条记录';
  end if;

  if normalized_status not in ('已通过', '已驳回') then
    raise exception '仅支持批量通过或驳回待审批记录';
  end if;

  normalized_time := coalesce(target_approval_time, timezone('utc', now()));

  if normalized_status = '已驳回' then
    normalized_reason := nullif(btrim(coalesce(target_rejection_reason, '')), '');
    if normalized_reason is null then
      raise exception '批量驳回时必须填写原因';
    end if;
  else
    normalized_reason := null;
  end if;

  with updated as (
    update public.applications
    set
      status = normalized_status,
      approval_time = normalized_time,
      approver_name = requester_name,
      rejection_reason = normalized_reason
    where id = any(normalized_ids)
      and status = '待审批'
    returning *
  ), logged as (
    insert into public.operation_logs (
      application_id,
      actor_user_id,
      actor_name,
      actor_role,
      action,
      details
    )
    select
      updated.id,
      auth.uid(),
      requester_name,
      requester_role,
      case when normalized_status = '已通过' then 'approve_application' else 'reject_application' end,
      jsonb_build_object(
        'mode', 'batch',
        'status', updated.status,
        'teacher_name', updated.teacher_name,
        'file_name', updated.file_name,
        'approval_time', updated.approval_time,
        'rejection_reason', updated.rejection_reason
      )
    from updated
    returning 1
  )
  select coalesce(array_agg(updated.id order by updated.id), '{}'::bigint[])
  into updated_ids
  from updated;

  if coalesce(array_length(updated_ids, 1), 0) = 0 then
    raise exception '未找到可更新的待审批记录';
  end if;

  return updated_ids;
end;
$$;

comment on function public.admin_bulk_change_application_status(bigint[], text, timestamptz, text) is
  '管理员批量更新待审批记录的状态，并逐条写入操作日志';

create or replace function public.admin_delete_rejected_application(target_application_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_role text;
  requester_name text;
  deleted_app public.applications%rowtype;
  delete_scope text;
begin
  select
    coalesce(role, 'teacher'),
    coalesce(nullif(btrim(coalesce(full_name, '')), ''), nullif(btrim(coalesce(username, '')), ''), '未命名用户')
  into requester_role, requester_name
  from public.profiles
  where id = auth.uid();

  requester_role := coalesce(requester_role, 'teacher');
  requester_name := coalesce(requester_name, '未命名用户');

  delete from public.applications
  where id = target_application_id
    and status = '已驳回'
    and (
      requester_role = 'admin'
      or user_id = auth.uid()
    )
  returning * into deleted_app;

  if deleted_app.id is null then
    raise exception '未找到可删除的已驳回记录';
  end if;

  delete_scope := case when requester_role = 'admin' then 'admin' else 'owner' end;

  insert into public.operation_logs (
    application_id,
    actor_user_id,
    actor_name,
    actor_role,
    action,
    details
  )
  values (
    deleted_app.id,
    auth.uid(),
    requester_name,
    requester_role,
    'delete_rejected_application',
    jsonb_build_object(
      'mode', 'single',
      'scope', delete_scope,
      'status', deleted_app.status,
      'teacher_name', deleted_app.teacher_name,
      'file_name', deleted_app.file_name,
      'rejection_reason', deleted_app.rejection_reason
    )
  );

  return deleted_app.id;
end;
$$;

comment on function public.admin_delete_rejected_application(bigint) is
  '允许管理员或记录所属教师物理删除已驳回记录，并写入操作日志';

create or replace function public.admin_bulk_delete_rejected_applications(target_application_ids bigint[])
returns bigint[]
language plpgsql
security definer
set search_path = public
as $$
declare
  requester_role text;
  requester_name text;
  normalized_ids bigint[];
  deleted_ids bigint[];
begin
  select
    coalesce(role, 'teacher'),
    coalesce(nullif(btrim(coalesce(full_name, '')), ''), nullif(btrim(coalesce(username, '')), ''), '未命名用户')
  into requester_role, requester_name
  from public.profiles
  where id = auth.uid();

  requester_role := coalesce(requester_role, 'teacher');
  requester_name := coalesce(requester_name, '未命名用户');
  normalized_ids := array(
    select distinct unnest(coalesce(target_application_ids, '{}'::bigint[]))
  );

  if requester_role <> 'admin' then
    raise exception '只有管理员可以批量删除已驳回记录';
  end if;

  if coalesce(array_length(normalized_ids, 1), 0) = 0 then
    raise exception '请先选择至少一条记录';
  end if;

  with deleted as (
    delete from public.applications
    where id = any(normalized_ids)
      and status = '已驳回'
    returning *
  ), logged as (
    insert into public.operation_logs (
      application_id,
      actor_user_id,
      actor_name,
      actor_role,
      action,
      details
    )
    select
      deleted.id,
      auth.uid(),
      requester_name,
      requester_role,
      'delete_rejected_application',
      jsonb_build_object(
        'mode', 'batch',
        'scope', 'admin',
        'status', deleted.status,
        'teacher_name', deleted.teacher_name,
        'file_name', deleted.file_name,
        'rejection_reason', deleted.rejection_reason
      )
    from deleted
    returning 1
  )
  select coalesce(array_agg(deleted.id order by deleted.id), '{}'::bigint[])
  into deleted_ids
  from deleted;

  if coalesce(array_length(deleted_ids, 1), 0) = 0 then
    raise exception '未找到可删除的已驳回记录';
  end if;

  return deleted_ids;
end;
$$;

comment on function public.admin_bulk_delete_rejected_applications(bigint[]) is
  '管理员批量物理删除已驳回记录，并逐条写入操作日志';

revoke all on function public.admin_change_application_status(bigint, text, timestamptz, text) from public;
revoke all on function public.admin_bulk_change_application_status(bigint[], text, timestamptz, text) from public;
revoke all on function public.admin_delete_rejected_application(bigint) from public;
revoke all on function public.admin_bulk_delete_rejected_applications(bigint[]) from public;

grant execute on function public.admin_change_application_status(bigint, text, timestamptz, text) to authenticated;
grant execute on function public.admin_bulk_change_application_status(bigint[], text, timestamptz, text) to authenticated;
grant execute on function public.admin_delete_rejected_application(bigint) to authenticated;
grant execute on function public.admin_bulk_delete_rejected_applications(bigint[]) to authenticated;

notify pgrst, 'reload schema';

commit;
